spring:
  application:
    name: user-service
    #Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/userDB
    username: embarkx
    password: embarkx

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#Server configuration
server:
  port: 8082